search by id
Hartooro/news-project-solo- pull request #5
Opened 2022-11-15 16:32 UTC by Hartooro

2022-11-15 16:48 UTC, xViolaine requested changes

2022-11-15 16:48 UTC, xViolaine commented on __tests__/app.test.js
> +
This test needs to be more extensive.
You are correct about checking for the specific article_id, so good job here, but you should still use expect.objectContaining or .toMatchObject as well as just checking the other properties again (with expect.any(Number/String/etc.)

2022-11-15 16:48 UTC, xViolaine commented on __tests__/app.test.js
> +    });
If an ID is not present, we don't want to return an empty array, we want to return a 404 + Error, not a 200

2022-11-15 16:48 UTC, xViolaine commented on models.js
> +        } else {
If the ID that is put in is a number, but the article doesn't exist, then we want to return a 404, not an empty array

2022-11-15 16:48 UTC, xViolaine commented on controllers.js
> +            res.status(200).send(result)
see comment below

2022-11-16 11:17 UTC, Rayhaan2k9 approved these changes
Nice work! 👏

2022-11-16 11:23 UTC, merged